USE DATABASE TEST_DB;
USE SCHEMA PUBLIC;

-- Pretend this is a "new batch"
CREATE OR REPLACE TEMP TABLE SALES_BATCH AS
SELECT * FROM SALES
QUALIFY ROW_NUMBER() OVER (ORDER BY RANDOM()) <= 300;

-- Mutate some rows to simulate updates
UPDATE SALES_BATCH
SET QTY = QTY + 1
WHERE ORDER_ID IN (SELECT ORDER_ID FROM SALES_BATCH QUALIFY ROW_NUMBER() OVER (ORDER BY RANDOM()) <= 50);

-- Target table for upsert demo
CREATE OR REPLACE TABLE SALES_TARGET LIKE SALES;
INSERT INTO SALES_TARGET SELECT * FROM SALES WHERE ORDER_ID <= 2000;

MERGE INTO SALES_TARGET t
USING SALES_BATCH s
  ON t.ORDER_ID = s.ORDER_ID
WHEN MATCHED THEN UPDATE SET
  CUSTOMER_ID = s.CUSTOMER_ID,
  ORDER_TS    = s.ORDER_TS,
  PRODUCT     = s.PRODUCT,
  QTY         = s.QTY,
  UNIT_PRICE  = s.UNIT_PRICE,
  REGION      = s.REGION
WHEN NOT MATCHED THEN INSERT (
  ORDER_ID, CUSTOMER_ID, ORDER_TS, PRODUCT, QTY, UNIT_PRICE, REGION
) VALUES (
  s.ORDER_ID, s.CUSTOMER_ID, s.ORDER_TS, s.PRODUCT, s.QTY, s.UNIT_PRICE, s.REGION
);

SELECT COUNT(*) FROM SALES_TARGET;
