REATE OR REPLACE DATABASE TEST_DB;
CREATE OR REPLACE SCHEMA TEST_DB.PUBLIC;

USE DATABASE TEST_DB;
USE SCHEMA PUBLIC;

CREATE OR REPLACE TABLE SALES (
  ORDER_ID      NUMBER,
  CUSTOMER_ID   NUMBER,
  ORDER_TS      TIMESTAMP_NTZ,
  PRODUCT       STRING,
  QTY           NUMBER,
  UNIT_PRICE    NUMBER(10,2),
  REGION        STRING
);

-- Quick check
DESC TABLE SALES;
