USE DATABASE TEST_DB;
USE SCHEMA PUBLIC;

-- Generate 1..1000 with random values
CREATE OR REPLACE TEMP TABLE NUMS AS
SELECT
  SEQ4() + 1 AS N,
  UNIFORM(1, 100000, RANDOM()) AS RAND_INT,
  (UNIFORM(0, 100000, RANDOM()) / 100::FLOAT) AS RAND_DEC,
  RANDOM() AS RAND_FLOAT_0_1
FROM TABLE(GENERATOR(ROWCOUNT => 1000));

-- Preview
SELECT * FROM NUMS ORDER BY N LIMIT 20;

-- Basic stats
SELECT
  COUNT(*) AS rows,
  MIN(RAND_INT) AS min_int,
  MAX(RAND_INT) AS max_int,
  AVG(RAND_INT) AS avg_int,
  STDDEV(RAND_INT) AS stddev_int
FROM NUMS;

-- Top 10 by RAND_INT
SELECT *
FROM NUMS
ORDER BY RAND_INT DESC
LIMIT 10;

-- Example: bucket distribution (by 10k ranges)
SELECT
  FLOOR(RAND_INT / 10000) * 10000 AS bucket_start,
  COUNT(*) AS cnt
FROM NUMS
GROUP BY 1
ORDER BY 1;
