USE DATABASE TEST_DB;
USE SCHEMA PUBLIC;

-- Ensure the target table exists (from setup script)
-- SALES(ORDER_ID, CUSTOMER_ID, ORDER_TS, PRODUCT, QTY, UNIT_PRICE, REGION)

TRUNCATE TABLE SALES;

-- Insert 5,000 synthetic orders
INSERT INTO SALES
SELECT
  SEQ4() + 1 AS ORDER_ID,
  UNIFORM(1, 200, RANDOM()) AS CUSTOMER_ID,
  DATEADD(
    'minute',
    UNIFORM(0, 60 * 24 * 30, RANDOM()),
    DATEADD('day', -UNIFORM(0, 180, RANDOM()), CURRENT_TIMESTAMP())
  )::TIMESTAMP_NTZ AS ORDER_TS,
  ARRAY_CONSTRUCT('MFP','LP','CP','TC','DAS')[UNIFORM(0,4,RANDOM())]::STRING AS PRODUCT,
  UNIFORM(1, 15, RANDOM()) AS QTY,
  (UNIFORM(10, 500, RANDOM()) + UNIFORM(0, 99, RANDOM())/100::FLOAT)::NUMBER(10,2) AS UNIT_PRICE,
  ARRAY_CONSTRUCT('AKL','WLG','CHC','HAM','TGA')[UNIFORM(0,4,RANDOM())]::STRING AS REGION
FROM TABLE(GENERATOR(ROWCOUNT => 5000));

-- Quick sanity checks
SELECT
  COUNT(*) AS rows,
  MIN(ORDER_TS) AS min_ts,
  MAX(ORDER_TS) AS max_ts,
  COUNT(DISTINCT CUSTOMER_ID) AS distinct_customers
FROM SALES;

-- Revenue by region
SELECT
  REGION,
  SUM(QTY * UNIT_PRICE) AS revenue
FROM SALES
GROUP BY REGION
ORDER BY revenue DESC;
